### ISSUE TITLE
Error on linker???

### ISSUE THREAD

**Issue by ainghilleri** [tonton81/FlexCAN_T4#11]
Hi Antonio,
first of all, thank you very much for the wonderful work you have done with this library.
I had already tested your library with a simple example with the Teensy 4 card and everything worked.
Now reopening the example and recompiling I get the following error:

Compiling 'CanBus1' for 'Teensy 4.0'

Error linking for board Teensy 4.0
Build failed for project 'CanBus1'
 
CanBus1.cpp.o: In function FlexCAN_T4_Base::FlexCAN_T4_Base()
FlexCAN_T4.h:285: undefined reference to vtable for FlexCAN_T4_Base
 
collect2.exe*: error: ld returned 1 exit status

I also tried to download your library again, clean the solution, recompile everything but always give the usual error.
Lately I have only updated the Arduino IDE to the latest version 1.8.12, is there any incompatibility with this version?
Can you help me out please?
Thanks in advance...
A:I:)

**Comment by tonton81** [comment]
Validate you have teensy 4 selected under boards
