### ISSUE TITLE
CAN alternative pin state is reset in .begin() if not in use

### ISSUE THREAD

**Issue by noisymime** [tonton81/FlexCAN_T4#17]
When the `CAN0.begin()` function is called, it checks whether the default or alternative pins should be used. If the default pins are used, the config of the alternative pins is set to 0. 

This means that if pins 29 or 30 (On a Teensy 3.5 or 3.6) are in use as outputs, they will no longer function as their config has been reset. 

**Steps to reproduce (Using Teensy 3.5 or 3.6):**
* Set `pinMode(29, OUTPUT)` and `pinMode(30, OUTPUT)` 
* Run `Can0.begin()`
* Try to perform an output on pin 29 or 30 (Eg `digitalWrite(29, HIGH)`)

**Actual Behaviour:**
The pins (29 and 30) will not output a high state

**Expected behaviour:**
The pin state of 29 and 30 should be retained because they are not in use by CAN0.

**Comment by civic2016** [comment]
Make sure you have an updated copy on this repo, this has been referenced on issue #14
