### ISSUE TITLE
Overun error doubt

### ISSUE THREAD

**Issue by antodom** [tonton81/FlexCAN_T4#18]
Hi there, 

Are there any way using this library of knowing when a CAN frame has been overwritten due to an overrun error?.

Thanks in advance.

**Comment by tonton81** [comment]
msg.overrun would return 1 if that was so. Unless you were polling, you shouldn't get overruns in interrupt mode

**Comment by antodom** [comment]
Hi there again,

Thanks, I was not aware of this flag in the message structure.
