### ISSUE TITLE
problem reading msg identifier

### ISSUE THREAD

**Issue by leonardoBolzonella** [tonton81/FlexCAN_T4#19]
Hello, I have been testing FlexCAN using a Teensy3.6 to send data to a custom ECU that uses a custom can code.  I have changed the header file so that the msg.id is of type uint16_t, in order to match the custom can code. When a message is sent from the ECU with identifier 0x901 (1001 0000 0001), the teensy is reading id = 0x101  (001 0000 0001). I tried reverting to its original type (uint32_t) but nothing changed. Any idea why only 11 bits are being read in the id, instead of the 12 I was expecting? 

I hope the question is clear, 
Cheers,
Leo

**Comment by tonton81** [comment]
try setting msg.flags.extended to 1

**Comment by leonardoBolzonella** [comment]
Thanks for the quick reply! Should it set it in the frame being sent or is it a setting for the CAN receiver code? 
Sorry if this sounds like an obvious question but this is my first time using CAN protocol.

**Comment by tonton81** [comment]
sending

**Comment by leonardoBolzonella** [comment]
Worked, thank you!
