### ISSUE TITLE
CANx to Pin table

### ISSUE THREAD

**Issue by rcrowder** [tonton81/FlexCAN_T4#20]
Add into the Readme.md file a table that shows which Pins the CANx template parameters are associated with.

I'm provisioning to experiment with this library in a project, and currently hunting down which pins this library will use on a Teensy 4.0

**Comment by rcrowder** [comment]
Update: I see from the Teensy 4.0 "Pins" diagram (https://www.pjrc.com/store/teensy40.html), that it shows 2+1 CAN ports: CTX1+CRX1, Alt. CTX1+Alt. CRX1, and CTX2+CRX2. So I can assume from that that the CAN1, CAN2, CAN3 in some way line up with those pins.

**Comment by tonton81** [comment]
yes, that is correct
