### ISSUE TITLE
Importing error 

### ISSUE THREAD

**Issue by Chase-Arline** [tonton81/FlexCAN_T4#21]
I just downloaded the newest version off of Git and I am getting this error from just attempting to import FlexCAN_T4

"\Documents\Arduino\libraries\FlexCAN_T4/circular_buffer.h:38:10: fatal error: algorithm: No such file or directory
 #include <algorithm>
          ^~~~~~~~~~~
"
We do not have this issue with earlier versions of FlexCAN_T4, but we do with the most recent master version.

This is on Arduino version 1.8.13

**Comment by tonton81** [comment]
make sure teensy is selected in the IDE

**Comment by Chase-Arline** [comment]
This was the issue, sorry for not realizing
