### ISSUE TITLE
CAN Errors reset

### ISSUE THREAD

**Issue by SimonFilgis** [tonton81/FlexCAN_T4#28]
How to reset CAN errors?

**Comment by tonton81** [comment]
what errors? the error counters? they reset when there is activity on the bus

**Comment by SimonFilgis** [comment]
Hi Antonio,

Yes, this is how it works. This is not a driver issue! It was only unclear
to me.

I need to show all errors that happened within the last 10 seconds. Do you
have an idea how to achieve this? I mean how can I be sure that no error is
"forgotten" due to activity before I have time to read it.

I need to dig into the code again...

Good weekend,

Simon

--
Hard- and Softwaredevelopment Consultant
Ingenieurbüro-Filgis
USt-IdNr.: DE305343278

**Comment by tonton81** [comment]
latest commit added error reporting, that may be useful to you
