### ISSUE TITLE
CANFD

### ISSUE THREAD

**Issue by khalm-github** [tonton81/FlexCAN_T4#3]
Hi, i am not expert of teensy and i was excited to use its CANFD but i got upset. i set two nodes (TX and RX), i am using MCP2562FD transceiver, i uploaded the example for the two board without any problems, but i got nothing on the can line, also i got nothing on the serial monitor. i am working for 3 days on that and i could not find where is the problem, i review the wiring many times and its look like right, did i forget something ! or someone faced the same issues before !
This is what i see on the serial monitor of the receiver
![Capture0](https://user-images.githubusercontent.com/53215889/70707962-b944db80-1cd9-11ea-8d87-a83f71abff52.PNG)

i used this code for receiving
![RX](https://user-images.githubusercontent.com/53215889/70707963-b9dd7200-1cd9-11ea-91dd-7509dfe976a6.PNG)

and this for transmitting
![TX](https://user-images.githubusercontent.com/53215889/70707964-b9dd7200-1cd9-11ea-86bd-6c11b3852b73.PNG)

i followed this diagram for wiring, but i connected  STBY pin of the transceiver just to the ground!
![wiring](https://user-images.githubusercontent.com/53215889/70708270-6586c200-1cda-11ea-8da1-5e23de9aa487.PNG)

**Comment by tonton81** [comment]
In setup(), you need to define a callback and interrupts:


 FD.enableMBInterrupts();

Then in loop() you need to enable the data buffer:
FD.events();

**Comment by khalm-github** [comment]
Thanks you very much for your quick response, but its still no big difference. i would be thankful if you notice me about any other thing may cause this issue .

now my TX code is like that:
![TX](https://user-images.githubusercontent.com/53215889/70713626-b4d2ef80-1ce6-11ea-80bc-313d5a414378.PNG)

and RX code:

![RX](https://user-images.githubusercontent.com/53215889/70713647-bf8d8480-1ce6-11ea-911a-07eeda6c9aaa.PNG)

and on the serial monitor just a white screen

![Capture0](https://user-images.githubusercontent.com/53215889/70713696-d207be00-1ce6-11ea-8dcb-21e8715f9870.PNG)

Is there anything that may be i did wrong !

**Comment by tonton81** [comment]
Is your transceiver enabled? If not you need to drive the line LOW to enable it

**Comment by khalm-github** [comment]
i will check that again tomorrow because i leaved now then i will back
another hint; what do you mean by drive the line low, i think the UART take control of all pins after serial.begin(), or do you mean something else !

**Comment by tonton81** [comment]
The transceiver enable pin, dont know if yours has one or not, didnt have time to check the datasheet of it, but for sure begin() has to be absolutely called first before the rest

**Comment by khalm-github** [comment]
no my transciever does not have enable pin. tomorrow i will check again the code, thanks Sir

This is my transciever MCP2562FD from microship

![MCP2562FD](https://user-images.githubusercontent.com/53215889/70731404-ecea2a80-1d06-11ea-8ea3-87bc5330735b.png)

**Comment by khalm-github** [comment]
Hi, i modified the code as you mention, and now i got the old output again.

![Capture0](https://user-images.githubusercontent.com/53215889/70788626-970e9480-1d91-11ea-8fd8-1283da0ab83b.PNG)

i really wondering why it does not work! should i replace the transceiver with another type.

also i disconnect the transceiver and connect the rx and tx pins 30 and 31 for teensy on the oscilloscope and i got signal

**Comment by tonton81** [comment]
Check if the transceiver CANH and CANL lines are parallel between eacy Teensy, and that both Teensies share a common ground path

**Comment by tonton81** [comment]
Did you get up and running in CANFD mode yet?
I've posted examples of TeensyCAN running CANFD in 8Mbps mode talking between nodes, perhaps you can use that to rule out software issue to check the wiring setup

**Comment by khalm-github** [comment]
Hello, sorry for late reply, but i was in a long vacation!

yes the CANFD mode is working now, the STBY pin of the transceiver was not connected, after i connect it to the ground, its worked fine. i test only one teensy. nowadays i am going on test 10 teensy in CANFD mode, after finished, may be i will  back here to give my feedback !
