### ISSUE TITLE
ISOTP single frame protocol is not implemented for messages less than 8 bytes

### ISSUE THREAD

**Issue by fredmcc** [tonton81/FlexCAN_T4#30]
I noticed that when sending short isotp messages they are being sent as the first frame (FF) of a multi frame message rather than as a single frame (SF) message which is the correct way for messages less than 8 bytes. 

Also if ISOTP_data config.len is set to the message length when sending a message it is being used to set the length of the first CAN frame, so when it is greater than 8 it creates an error. 

I will submit a pull request with fixes for these 2 issues.

**Comment by tonton81** [comment]
hmm, I just noticed, what if a buffer of less than 6 bytes it fed to the function?

`
memmove(&msg.buf[2], &buf[0], 6);
`
