### ISSUE TITLE
undefined reference to vtable for FlexCAN_T4_Base

### ISSUE THREAD

**Issue by corndog2000** [tonton81/FlexCAN_T4#32]
I am getting this error message when trying to compile my project files that use FlexCAN_T4.

```
Error linking for board Teensy 4.1
Build failed for project 'main'
 
main.cpp.o: In function FlexCAN_T4_Base::FlexCAN_T4_Base()
FlexCAN_T4.h:323: undefined reference to vtable for FlexCAN_T4_Base
 
collect2.exe*: error: ld returned 1 exit status
```

I downloaded the current github repo and replaced the files in the hardware libraries folder in the Arduino IDE root.

This happens when I try to build my project using Visual Micro with the "No Optimization" option selected.

**Comment by tonton81** [comment]
make sure you are running a recent arduino IDE with teensyduino, also with a demo sketch loaded. The error points at your main and i don't see your code so I can't see if it's a code problem
