### ISSUE TITLE
Undefined function is not pure virtual, causing undefined vtable linker error

### ISSUE THREAD

**Issue by DeanIsMe** [tonton81/FlexCAN_T4#51]
https://github.com/tonton81/FlexCAN_T4/blob/98654c7844408b536a44c3f3693a9c9a7335b21a/FlexCAN_T4.h#L331

`virtual uint8_t getFirstTxBoxSize();`
Should be changed to pure virtual (or defined).
`virtual uint8_t getFirstTxBoxSize() = 0;`

Otherwise, when compiling with optimization off `-O0`, I get the linker error 
`undefined reference to 'vtable for FlexCAN_T4_Base'`

Note that this error doesn't appear with other optimization levels.

**Comment by tonton81** [comment]
Thanks, updated
https://github.com/tonton81/FlexCAN_T4/commit/82b12e637b9409dfe8de054654de7f7224bd14a1
