### ISSUE TITLE
ID issue with <FlexCAN_T4.h>

### ISSUE THREAD

**Issue by Cand0o** [tonton81/FlexCAN_T4#75]
Hi all,

I'm using a Teensy 4.1 and want to communicate with motor.
I have a ID issue. Below, my ID configuration.

txBufferTd.id = 0x0CF003d0; 
txBufferTd.flags.extended = 1;
txBufferTd.len = 8;

When I want to read the ID, I have :
ID: 0xCF003D0

One "0" is missing, someone have any ideas ?

Thx,

Cand0o

**Comment by tonton81** [comment]
it's the same with and without leading zeros, usually in HEX we don't display leading zeros but if you want it to show then pad it

**Comment by Cand0o** [comment]
Ok thx a lot for this information.
